### ISSUE TITLE
[CI] Add D401 to linting

### ISSUE THREAD

**Issue by sed-i** [canonical/observability-libs#27]
### Enhancement Proposal

> I know our linting is not checking this, but just in case some day we decide to check it, we may get:
> 
> `D401: First line should be in imperative mood (perhaps 'Return', not 'Returns') [D401]`

_Originally posted by @Abuelodelanada in https://github.com/canonical/prometheus-k8s-operator/pull/373#discussion_r983896328_
      

---

`$ rg '"""\w+s\s' .` returns a lot of matches.

**Comment by lucabello** [comment]
After lots of investigation, it turns out the reason why we're not checking for D401 is because we can't; the "google convention" for docstrings (which we follow in all of our repos) explicitly ignores D401 in all linters (tried with flake and ruff), so it's not even possible to enable it.

Closing!
